[mypy]
python_version = 3.11
strict = false
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = True
namespace_packages = True
explicit_package_bases = True

[mypy-tests.*]
ignore_errors = True
